- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - debug: var=ansible_config_file

    - debug: msg=foo

    - debug:
        msg: "retrieve: {{ lookup('ansible.builtin.config', 'ANSIBLE_COW_PATH') }}"
