- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - debug: var=ansible_config_file

    - debug: msg=foo

    - debug:
        msg: "retrieve: {{ lookup('ansible.builtin.config', 'COLOR_CHANGED') }}"

    - shell: ls -la; cat ansible.cfg; pwd
      register: shell_output
      failed_when: false

    - debug: var=shell_output

    - community.general.ldap_search:
        dn: "ou=groups,dc=example,dc=com"
      register: foobar
