- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - debug: var=ansible_config_file

    - debug: msg=foo

    - debug:
        msg: "retrieve: {{ lookup('ansible.builtin.config', 'COLOR_CHANGED') }}"

    - shell: ls -la; cat ansible.cfg
      register: shell_output

    - debug: var=shell_output
